### ISSUE TITLE
NuclearMusic not working on PetteriM1 edition of nukkitx

### ISSUE THREAD

**Issue by dongmin-dev** [PetteriM1/NuclearMusic#1]
Worked great at the vanilla NukkitX, but the noteblock doesn't play songs at NukkitX PetteriM1 edition.

**Comment by PetteriM1** [comment]
Is there an error or something?

**Comment by dongmin-dev** [comment]
> Is there an error or something?

It loads ok, but not playing.
I solved this by replacing the plugin at your Gdrive.
